apiVersion: apps/v1
kind: Deployment
metadata:
  name: authv2
  labels:
    app: authv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authv2
  template:
    metadata:
      labels:
        app: authv2
    spec:
      terminationGracePeriodSeconds: 3000

      containers:
        - name: authv2
          image: authv2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: "128Mi"
            requests:
              cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: authv2
  labels:
    run: authv2
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    - port: 8080
  selector:
    app: authv2

